services:
  - type: web
    name: criador-de-form
    runtime: docker
    plan: free
    envVars:
      - key: COOKIE_SECURE
        value: "true"
      - key: FRONTEND_ORIGIN
        value: https://criador-de-form.onrender.com
      - key: FRONTEND_BASE_URL
        value: https://criador-de-form.onrender.com
      - key: GOOGLE_REDIRECT_URL
        value: https://criador-de-form.onrender.com/api/auth/google/callback
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
